# Your theme's name must begin with Plastic, e.g. Plastic Horses
name: Plastic B

palette:
  dodger_blue: '#1085FF'
  atlantis: '#69c52e'
  bright_turquoise: '#08E8DE'
  bunker: '#0D1117'
  cadet_blue: '#A9B2C3'
  cadet_blue_1A: '#A9B2C31A'
  cadet_blue_33: '#A9B2C333'
  cornflower_blue: '#61AFEF'
  pale_blue: '#17E5E650'
  electric_violet: '#8B00FF'
  fountain_blue: '#56B6C2'
  harvest_gold: '#FFCB70'
  iron: '#D4D7D9'
  lavender: '#B57EDC'
  olivine: '#98C379'
  rob_roy: '#E9D16C'
  shark: '#21252B'
  shuttle_gray: '#5F6672'
  sunglo: '#E06C75'
  whiskey: '#FFAB70'
  woodsmoke: '#181A1F'
  transparent: '#00000000'
  valencia: '#D74E42'
  debug_red: '#931C06'
  white: '#ffffff'

terminal:
  terminal.ansiBlack: shark
  terminal.ansiBlue: cornflower_blue
  terminal.ansiCyan: fountain_blue
  terminal.ansiGreen: olivine
  terminal.ansiMagenta: lavender
  terminal.ansiRed: sunglo
  terminal.ansiYellow: whiskey
  terminal.ansiWhite: cadet_blue
  terminal.ansiBrightBlack: shuttle_gray
  terminal.ansiBrightBlue: dodger_blue
  terminal.ansiBrightCyan: bright_turquoise
  terminal.ansiBrightGreen: atlantis
  terminal.ansiBrightMagenta: electric_violet
  terminal.ansiBrightRed: valencia
  terminal.ansiBrightYellow: rob_roy
  terminal.ansiBrightWhite: iron

default_syntax:
  # comments
  shuttle_gray:
    - comment
    - punctuation.definition.comment # start and end of comment blocks
  # functions
  whiskey:
    - entity
    - entity.name.function
    - support.function
    - punctuation.definition.entity # css . and # for classes and IDs
  # import, export, return etc.
  sunglo:
    - keyword
    - punctuation.definition.directive # preprocessor hashes
    - punctuation.definition.keyword # css @ in @media queries
  # primitives
  fountain_blue:
    - constant
    - keyword.other
    - support.type
  # const, var, class etc. and React JSX component tag
  cornflower_blue:
    - storage
    - support.class
    - support.constant
    - variable.language # this
  # anything in quotes
  olivine:
    - string
    - punctuation.definition.string
    - markup.inline
  # html tags
  harvest_gold:
    - entity.name
  # variables
  iron:
    - support.type.property-name
    - support.variable
    - variable

normal_syntax:
  # quotes, terminators etc.  
  cadet_blue:
    - meta.brace
    - punctuation

deprioritised_syntax:
  # quotes, terminators etc.
  shuttle_gray:
    - meta.brace
    - punctuation

styles:
  bold:
    - markup.bold
    - punctuation.definition.bold
    - entity.other.attribute-name.id # css ID
  italic:
    - markup.italic
    - punctuation.definition.italic

workbench:
  # green
  olivine:
    - gitDecoration.untrackedResourceForeground
  # blue
  cornflower_blue:
    - debugConsole.infoForeground
    - gitDecoration.modifiedResourceForeground
  dodger_blue:
    - activityBarBadge.background
    - button.background
    - activityBar.activeBorder
    - editor.wordHighlightBorder
    - editor.wordHighlightStrongBorder
    - editorInfo.foreground
    - editorLightBulbAutoFix.foreground
    - editorOverviewRuler.infoForeground
    - focusBorder
    - inputOption.activeBorder
    - inputValidation.infoBackground
    - inputValidation.infoBorder
    - peekView.border
    - tab.activeBorderTop
  # warning. squiggly underlines, find match errors etc.
  rob_roy:
    - editorLightBulb.foreground
    - editorOverviewRuler.warningForeground
    - editorWarning.foreground
    - inputValidation.warningBackground
    - inputValidation.warningBorder
    - list.warningForeground
  # error. squiggly underlines, find match errors etc.
  valencia:
    - gitDecoration.deletedResourceForeground
    - editorError.foreground
    - editorOverviewRuler.errorForeground
    - errorForeground
    - inputValidation.errorBackground
    - inputValidation.errorBorder
    - list.errorForeground
  # borders that separate the panels, sidebars, tabs etc.
  bunker:
    - activityBar.border
    - contrastBorder
    - dropdown.border
    - editorGroup.border
    - editorOverviewRuler.border
    - input.background
    - inputValidation.infoForeground
    - inputValidation.warningForeground
    - notificationCenter.border
    - notificationToast.border
    - notifications.border
    - panel.border
    - sideBar.border
    - statusBar.border
    - tab.border
    - titleBar.border
  # editor, titlebar, and activity bar background
  shark:
    - activityBar.background
    - editor.background
    - sideBarSectionHeader.background
    - statusBar.background
    - tab.activeBackground
    - titleBar.activeBackground
    - titleBar.inactiveBackground
  # sidebar, terminal, inactive tabs etc.
  woodsmoke:
    - activityBar.dropBackground
    - debugToolBar.background
    - dropdown.background
    - editorGroup.background
    - editorGroupHeader.tabsBackground
    - editorHoverWidget.background
    - editorSuggestWidget.background
    - editorWidget.background
    - notificationCenterHeader.background
    - notifications.background
    - panel.background
    - peekViewEditor.background
    - peekViewResult.background
    - peekViewTitle.background
    - sideBar.background
    - statusBar.noFolderBackground
    - statusBarItem.hoverBackground
    - tab.inactiveBackground
  # line numbers, muted items
  shuttle_gray:
    - activityBar.inactiveForeground
    - editorLineNumber.foreground
    - tab.inactiveForeground
    - titleBar.inactiveForeground
  # text
  cadet_blue:
    - editorCursor.foreground
    - statusBar.foreground
    - terminal.foreground
  # braket matching
  pale_blue:
    - editorBracketMatch.background
  # editor text, active tab, active line number, active list text etc. Search match borders
  iron:
    - editor.foreground
    - editorActiveLineNumber.foreground
    - list.inactiveSelectionForeground
    - peekViewResult.selectionForeground
    - tab.activeForeground
    - titleBar.activeForeground
  # ui flourishes: whitespace, indent guide, ruler, line highlight
  cadet_blue_1A:
    - editor.lineHighlightBackground
    - editor.selectionHighlightBackground
    - editorIndentGuide.background
    - editorRuler.foreground
    - editorSuggestWidget.selectedBackground
    - editorWhitespace.foreground
    - list.hoverBackground
    - peekViewResult.selectionBackground
    - scrollbarSlider.background
    - tab.hoverBackground
  # active indent guide, selection, search match
  cadet_blue_33:
    - editor.selectionBackground
    - editorIndentGuide.activeBackground
    - list.activeSelectionBackground
    - list.focusBackground
    - list.inactiveSelectionBackground
    - peekViewEditor.matchHighlightBackground
    - peekViewResult.matchHighlightBackground
    - scrollbarSlider.activeBackground
    - scrollbarSlider.hoverBackground
  # a few tweaks to some backgrounds and highlights
  transparent:
    - editor.findMatchBackground
    - editor.findMatchHighlightBackground
    - editor.lineHighlightBorder
    - editor.wordHighlightBackground
    - editor.wordHighlightStrongBackground
    - scrollbar.shadow
    - widget.shadow
  # debugging bar
  debug_red:
    - statusBar.debuggingBackground 
  # some active items and text, that just looks better as pure white
  white:
    - statusBar.debuggingForeground
    - activityBar.foreground
    - activityBarBadge.foreground
